awsECRURL="077165079818.dkr.ecr.ap-northeast-2.amazonaws.com/myecr"
awsKey="aws-key"
awsRegion="ap-northeast-2"
branch="master"
commitMsg="cicd test"
directoryPath="service"
githubEmail="boykis82@gmail.com"
githubKey="github-key"
githubSSHURL="git@github.com:boykis82/cicd-test.git"
imageTag="green"

podTemplate(label: 'docker-build',
  containers: [
    containerTemplate(
      name: 'docker',
      image: 'docker',
      command: 'cat',
      ttyEnabled: true
    ),
    containerTemplate(
      name: 'argo',
      image: 'argoproj/argo-cd-ci-builder:latest',
      command: 'cat',
      ttyEnabled: true
    ),
  ],
  volumes: [ 
    hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock'), 
  ]
) {
  node('docker-build') {

		stage('Checkout') {
            container('docker'){
                checkout scm
            }
		}

		stage('Docker Build') {
			dir(path: "${directoryPath}/container"){
				container('docker') {
					image = docker.build("${awsECRURL}:${imageTag}","--build-arg COLOR=${imageTag} .")
				}
			}
		}

		stage('ECR Push') {
			container('docker') {
				docker.withRegistry("https://${awsECRURL}", "ecr:${awsRegion}:${awsKey}") {
					image.push()
				}
			}
		}

        stage('Deploy'){
            container('argo'){
                checkout(
                    [
                        $class: 'GitSCM',
                        extensions: scm.extensions,
                        branches: [
                            [
                                name: "*/${branch}"
                            ]
                        ],
                        userRemoteConfigs: [
                            [
                                url: "${githubSSHURL}",
                                credentialsId: "${githubKey}",
                            ]
                        ]
                    ]
                )
                sshagent(credentials: ["${githubKey}"]){
                    sh("""
                        #!/usr/bin/env bash
                        set +x
                        export GIT_SSH_COMMAND="ssh -oStrictHostKeyChecking=no"
                        git config --global user.email ${githubEmail}
                        git checkout ${branch}
                        cd ${directoryPath}/helm-charts
                        sed -i 's/tag:.*/tag: ${imageTag}/g' values.yaml
                        cd ../../../../
                        git commit -a -m ${commitMsg}
                        git remote set-url origin ${githubSSHURL}
                        git push -u origin master
                    """)
                }
            }
        }		
	}
}